export type EPermissionsRoutes =
  | "ASSISTENTE_EQUIPES"
  | "ASSISTENTE_AGENTES"
  | "ASSISTENTE_CONVERSAS"
  | "ASSISTENTE_RELATORIOS"
  | "ASSISTENTE_CONFIGURACOES"
  | "ASSISTENTE_TREINAMENTO"
  | "FINANCEIRO";

export type EPermissions = "ADMIN" | "ASSISTENTE" | "AGENTE";
